image: node:14.20.1

stages:
- test
- deploy

pages:
  stage: deploy
  script:
    - yarn
    - yarn build
    - mv dist public
  cache:
    paths:
    - node_modules
    - .cache
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
    - main

lint:
  stage: test
  allow_failure: true
  script:
    - yarn
    - yarn lint
  cache:
    paths:
    - node_modules
